import { Link } from "react-router-dom";
import { useStore } from "../../context/StoreContext";
export default function AdminCart(){
 const {cart,updateQty,removeFromCart,subtotal,tax,total}=useStore();
 return <div className="space-y-7">
  <div className="rounded-3xl border border-blue-100 bg-gradient-to-br from-blue-50 via-white to-indigo-50 p-6 shadow-sm sm:p-8"><p className="text-xs font-bold uppercase tracking-[.2em] text-blue-700">Admin Console</p><h1 className="mt-2 text-3xl font-extrabold">Product Cart</h1><p className="mt-2 text-sm text-stone-500">Products selected from the admin marketplace view are kept here for review. This cart does not create customer orders.</p></div>
  {!cart.length?<div className="rounded-3xl border border-dashed border-stone-300 bg-white p-12 text-center"><div className="text-5xl">🛒</div><h2 className="mt-4 text-2xl font-extrabold">Cart is empty</h2><p className="mt-2 text-sm text-stone-500">Go to Products and add listings to the admin cart.</p><Link to="/admin/products" className="btn-primary mt-6 inline-flex">Browse products</Link></div>:
  <div className="grid gap-6 lg:grid-cols-[1fr_340px]"><div className="space-y-3">{cart.map(x=><article key={x.id} className="flex gap-4 rounded-2xl border border-stone-200 bg-white p-4 shadow-sm"><img src={x.image} alt="" className="h-24 w-24 rounded-xl object-cover"/><div className="min-w-0 flex-1"><h3 className="font-extrabold">{x.name}</h3><p className="text-xs text-stone-500">{x.farmer||"Local Farmer"} · ${Number(x.price).toFixed(2)} {x.unit||""}</p><div className="mt-4 flex items-center gap-2"><button onClick={()=>updateQty(x.id,x.qty-1)} className="h-8 w-8 rounded-lg border">−</button><span className="w-8 text-center font-bold">{x.qty}</span><button onClick={()=>updateQty(x.id,x.qty+1)} className="h-8 w-8 rounded-lg border">+</button><button onClick={()=>removeFromCart(x.id)} className="ml-3 text-xs font-bold text-red-600">Remove</button></div></div><strong>${(Number(x.price)*x.qty).toFixed(2)}</strong></article>)}</div><aside className="h-fit rounded-3xl bg-navy-900 p-6 text-white"><p className="text-sm text-white/60">Cart summary</p><div className="mt-5 space-y-3 text-sm"><div className="flex justify-between"><span>Subtotal</span><span>${subtotal.toFixed(2)}</span></div><div className="flex justify-between"><span>Tax estimate</span><span>${tax.toFixed(2)}</span></div><div className="mt-4 flex justify-between border-t border-white/10 pt-4 text-lg font-extrabold"><span>Total</span><span>${total.toFixed(2)}</span></div></div><Link to="/admin/products" className="btn mt-6 block w-full bg-white/10 text-center text-white hover:bg-white/20">Continue browsing</Link></aside></div>}
 </div>
}
